// <auto-generated />
using System;
using LMS.Ovncr.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS.Ovncr.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS.Ovncr.Models.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbCauHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CauHoi")
                        .HasColumnType("ntext");

                    b.Property<string>("Dap1")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Dap2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Dap3")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Dap4")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DapAnDung")
                        .HasColumnType("int");

                    b.Property<int?>("IdDanhMucCauHoi")
                        .HasColumnType("int");

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDanhMucCauHoi");

                    b.ToTable("tbCauHoi", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbComputer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdOpenStack")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdProject")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("ntext");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VncUri")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdProject");

                    b.ToTable("tbComputer", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbDanhMucCauHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DanhMucCauHoi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tbDanhMucCauHoi", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbGiamSat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdProject")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ten")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdProject");

                    b.ToTable("tbGiamSat", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbHocVienLopHoc", b =>
                {
                    b.Property<int>("IdHocVienLopHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHocVienLopHoc"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("ntext");

                    b.Property<int?>("IdComputer")
                        .HasColumnType("int");

                    b.Property<string>("IdHocVien")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IdInstance")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("IdLopHoc")
                        .HasColumnType("int");

                    b.HasKey("IdHocVienLopHoc");

                    b.HasIndex("IdComputer");

                    b.HasIndex("IdHocVien");

                    b.HasIndex("IdLopHoc");

                    b.ToTable("tbHocVienLopHoc", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbInstance", b =>
                {
                    b.Property<int>("IdInstance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInstance"));

                    b.Property<int?>("IdProject")
                        .HasColumnType("int");

                    b.Property<string>("InstanceId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InstanceName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdInstance");

                    b.HasIndex("IdProject");

                    b.ToTable("tbInstance", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbKetQua", b =>
                {
                    b.Property<int>("IdKetQua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKetQua"));

                    b.Property<string>("DapAn")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double?>("Diem")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IdHocVien")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("IdKichBan")
                        .HasColumnType("int");

                    b.Property<int?>("IdLopHoc")
                        .HasColumnType("int");

                    b.Property<string>("UrlFileDapAn")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdKetQua");

                    b.HasIndex("IdHocVien");

                    b.HasIndex("IdKichBan");

                    b.HasIndex("IdLopHoc");

                    b.ToTable("tbKetQua", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbKichBan", b =>
                {
                    b.Property<int>("IdKichBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKichBan"));

                    b.Property<string>("DapAn")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HuongDanThucHanh")
                        .HasColumnType("ntext");

                    b.Property<int?>("IdKieuDanhGia")
                        .HasColumnType("int");

                    b.Property<string>("MaKichBan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MucTieu")
                        .HasColumnType("ntext");

                    b.Property<string>("NoiDung")
                        .HasColumnType("ntext")
                        .HasComment("Nội dung");

                    b.Property<string>("TenKichBan")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Tên kịch bản");

                    b.Property<string>("YeuCau")
                        .HasColumnType("ntext");

                    b.HasKey("IdKichBan");

                    b.HasIndex("IdKieuDanhGia");

                    b.ToTable("tbKichBan", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbKichBanNhom", b =>
                {
                    b.Property<int>("IdKichBanNhom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKichBanNhom"));

                    b.Property<int>("IdKichBan")
                        .HasColumnType("int");

                    b.Property<int>("IdNhom")
                        .HasColumnType("int");

                    b.HasKey("IdKichBanNhom");

                    b.HasIndex("IdKichBan");

                    b.HasIndex("IdNhom");

                    b.ToTable("tbKichBanNhom", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbKichBanSoDoMang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdKichBan")
                        .HasColumnType("int");

                    b.Property<int?>("IdSoDoMang")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdKichBan");

                    b.HasIndex("IdSoDoMang");

                    b.ToTable("tbKichBanSoDoMang", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbKieuDanhGium", b =>
                {
                    b.Property<int>("IdKieuDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKieuDanhGia"));

                    b.Property<string>("KieuDanhGia")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdKieuDanhGia");

                    b.ToTable("tbKieuDanhGia", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbKyThi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DanhMucCauHoi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Diem")
                        .HasColumnType("int");

                    b.Property<int?>("KyThi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ThoiGianBatDat")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tbKyThi", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbLichPhongLab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DenNgay")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdProject")
                        .HasColumnType("int");

                    b.Property<string>("IdUser")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("TuNgay")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("IdProject");

                    b.HasIndex("IdUser");

                    b.ToTable("tbLichPhongLab", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbLopHoc", b =>
                {
                    b.Property<int>("IdLopHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLopHoc"));

                    b.Property<int?>("IdProjectOs")
                        .HasColumnType("int")
                        .HasColumnName("IdProjectOS");

                    b.Property<string>("LopHoc")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ThongTin")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdLopHoc");

                    b.HasIndex("IdProjectOs");

                    b.HasIndex("NguoiTao");

                    b.ToTable("tbLopHoc", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbLopHocKichBan", b =>
                {
                    b.Property<int>("IdLopHocKichBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLopHocKichBan"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IdKichBan")
                        .HasColumnType("int");

                    b.Property<int?>("IdLopHoc")
                        .HasColumnType("int");

                    b.HasKey("IdLopHocKichBan");

                    b.HasIndex("IdKichBan");

                    b.HasIndex("IdLopHoc");

                    b.ToTable("tbLopHocKichBan", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbNhom", b =>
                {
                    b.Property<int>("IdNhom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNhom"));

                    b.Property<string>("Nhom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdNhom");

                    b.ToTable("tbNhom", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbProjectOpenStack", b =>
                {
                    b.Property<int>("IdProject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProject"));

                    b.Property<string>("ProjectId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdProject");

                    b.ToTable("tbProjectOpenStack", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.ToTable("tbSettings", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbSoDoMang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Path")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ten")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Uuid")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.ToTable("tbSoDoMang", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbSoDoMangMay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IdSoDoMang")
                        .HasColumnType("int");

                    b.Property<string>("Kieu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaMay")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenMay")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdSoDoMang");

                    b.ToTable("tbSoDoMangMay", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbSubmit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileKetQua")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IdHocVien")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("IdKichBan")
                        .HasColumnType("int");

                    b.Property<int?>("IdLopHoc")
                        .HasColumnType("int");

                    b.Property<string>("KetQua")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("Lan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayGio")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("tbSubmit", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbTinhTrangCv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TinhTrang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tbTinhTrangCV", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbTraLoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DapAnTraLoi")
                        .HasColumnType("int");

                    b.Property<int?>("Diem")
                        .HasColumnType("int");

                    b.Property<int?>("IdCauHoi")
                        .HasColumnType("int");

                    b.Property<int?>("IdKyThi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime");

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCauHoi");

                    b.HasIndex("IdKyThi");

                    b.ToTable("tbTraLoi", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbCauHoi", b =>
                {
                    b.HasOne("LMS.Ovncr.Models.TbDanhMucCauHoi", "IdDanhMucCauHoiNavigation")
                        .WithMany("TbCauHois")
                        .HasForeignKey("IdDanhMucCauHoi")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_tbCauHoi_tbDanhMucCauHoi");

                    b.Navigation("IdDanhMucCauHoiNavigation");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbComputer", b =>
                {
                    b.HasOne("LMS.Ovncr.Models.TbProjectOpenStack", "IdProjectNavigation")
                        .WithMany("TbComputers")
                        .HasForeignKey("IdProject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_tbComputer_tbProjectOpenStack");

                    b.Navigation("IdProjectNavigation");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbGiamSat", b =>
                {
                    b.HasOne("LMS.Ovncr.Models.TbProjectOpenStack", "IdProjectNavigation")
                        .WithMany("TbGiamSats")
                        .HasForeignKey("IdProject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_tbGiamSat_tbProjectOpenStack");

                    b.Navigation("IdProjectNavigation");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbHocVienLopHoc", b =>
                {
                    b.HasOne("LMS.Ovncr.Models.TbComputer", "IdComputerNavigation")
                        .WithMany("TbHocVienLopHocs")
                        .HasForeignKey("IdComputer")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_tbHocVienLopHoc_tbComputer");

                    b.HasOne("LMS.Ovncr.Models.AspNetUser", "IdHocVienNavigation")
                        .WithMany("TbHocVienLopHocs")
                        .HasForeignKey("IdHocVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_tbHocVienLopHoc_AspNetUsers");

                    b.HasOne("LMS.Ovncr.Models.TbLopHoc", "IdLopHocNavigation")
                        .WithMany("TbHocVienLopHocs")
                        .HasForeignKey("IdLopHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_tbHocVienLopHoc_tbLopHoc");

                    b.Navigation("IdComputerNavigation");

                    b.Navigation("IdHocVienNavigation");

                    b.Navigation("IdLopHocNavigation");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbInstance", b =>
                {
                    b.HasOne("LMS.Ovncr.Models.TbProjectOpenStack", "IdProjectNavigation")
                        .WithMany("TbInstances")
                        .HasForeignKey("IdProject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_tbInstance_tbProjectOpenStack");

                    b.Navigation("IdProjectNavigation");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbKetQua", b =>
                {
                    b.HasOne("LMS.Ovncr.Models.AspNetUser", "IdHocVienNavigation")
                        .WithMany("TbKetQuas")
                        .HasForeignKey("IdHocVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_tbKetQua_AspNetUsers");

                    b.HasOne("LMS.Ovncr.Models.TbKichBan", "IdKichBanNavigation")
                        .WithMany("TbKetQuas")
                        .HasForeignKey("IdKichBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_tbKetQua_tbKichBan");

                    b.HasOne("LMS.Ovncr.Models.TbLopHoc", "IdLopHocNavigation")
                        .WithMany("TbKetQuas")
                        .HasForeignKey("IdLopHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_tbKetQua_tbLopHoc");

                    b.Navigation("IdHocVienNavigation");

                    b.Navigation("IdKichBanNavigation");

                    b.Navigation("IdLopHocNavigation");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbKichBan", b =>
                {
                    b.HasOne("LMS.Ovncr.Models.TbKieuDanhGium", "IdKieuDanhGiaNavigation")
                        .WithMany("TbKichBans")
                        .HasForeignKey("IdKieuDanhGia")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_tbKichBan_tbKieuDanhGia");

                    b.Navigation("IdKieuDanhGiaNavigation");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbKichBanNhom", b =>
                {
                    b.HasOne("LMS.Ovncr.Models.TbKichBan", "IdKichBanNavigation")
                        .WithMany("TbKichBanNhoms")
                        .HasForeignKey("IdKichBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tbKichBanNhom_tbKichBan");

                    b.HasOne("LMS.Ovncr.Models.TbNhom", "IdNhomNavigation")
                        .WithMany("TbKichBanNhoms")
                        .HasForeignKey("IdNhom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tbKichBanNhom_tbNhom");

                    b.Navigation("IdKichBanNavigation");

                    b.Navigation("IdNhomNavigation");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbKichBanSoDoMang", b =>
                {
                    b.HasOne("LMS.Ovncr.Models.TbKichBan", "IdKichBanNavigation")
                        .WithMany("TbKichBanSoDoMangs")
                        .HasForeignKey("IdKichBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_tbKichBanSoDoMang_tbKichBan");

                    b.HasOne("LMS.Ovncr.Models.TbSoDoMang", "IdSoDoMangNavigation")
                        .WithMany("TbKichBanSoDoMangs")
                        .HasForeignKey("IdSoDoMang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_tbKichBanSoDoMang_tbSoDoMang");

                    b.Navigation("IdKichBanNavigation");

                    b.Navigation("IdSoDoMangNavigation");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbKyThi", b =>
                {
                    b.HasOne("LMS.Ovncr.Models.AspNetUser", "User")
                        .WithMany("TbKyThis")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_tbKyThi_AspNetUsers");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbLichPhongLab", b =>
                {
                    b.HasOne("LMS.Ovncr.Models.TbProjectOpenStack", "IdProjectNavigation")
                        .WithMany("TbLichPhongLabs")
                        .HasForeignKey("IdProject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_tbLichPhongLab_tbProjectOpenStack");

                    b.HasOne("LMS.Ovncr.Models.AspNetUser", "IdUserNavigation")
                        .WithMany("TbLichPhongLabs")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_tbLichPhongLab_AspNetUsers");

                    b.Navigation("IdProjectNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbLopHoc", b =>
                {
                    b.HasOne("LMS.Ovncr.Models.TbProjectOpenStack", "IdProjectOsNavigation")
                        .WithMany("TbLopHocs")
                        .HasForeignKey("IdProjectOs")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_tbLopHoc_tbProjectOpenStack");

                    b.HasOne("LMS.Ovncr.Models.AspNetUser", "NguoiTaoNavigation")
                        .WithMany("TbLopHocs")
                        .HasForeignKey("NguoiTao")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_tbLopHoc_AspNetUsers");

                    b.Navigation("IdProjectOsNavigation");

                    b.Navigation("NguoiTaoNavigation");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbLopHocKichBan", b =>
                {
                    b.HasOne("LMS.Ovncr.Models.TbKichBan", "IdKichBanNavigation")
                        .WithMany("TbLopHocKichBans")
                        .HasForeignKey("IdKichBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_tbLopHocKichBan_tbKichBan");

                    b.HasOne("LMS.Ovncr.Models.TbLopHoc", "IdLopHocNavigation")
                        .WithMany("TbLopHocKichBans")
                        .HasForeignKey("IdLopHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_tbLopHocKichBan_tbLopHoc");

                    b.Navigation("IdKichBanNavigation");

                    b.Navigation("IdLopHocNavigation");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbSoDoMangMay", b =>
                {
                    b.HasOne("LMS.Ovncr.Models.TbSoDoMang", "IdSoDoMangNavigation")
                        .WithMany("TbSoDoMangMays")
                        .HasForeignKey("IdSoDoMang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_tbSoDoMangMay_tbSoDoMang");

                    b.Navigation("IdSoDoMangNavigation");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbTraLoi", b =>
                {
                    b.HasOne("LMS.Ovncr.Models.TbCauHoi", "IdCauHoiNavigation")
                        .WithMany("TbTraLois")
                        .HasForeignKey("IdCauHoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_tbTraLoi_tbCauHoi");

                    b.HasOne("LMS.Ovncr.Models.TbKyThi", "IdKyThiNavigation")
                        .WithMany("TbTraLois")
                        .HasForeignKey("IdKyThi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_tbTraLoi_tbKyThi");

                    b.Navigation("IdCauHoiNavigation");

                    b.Navigation("IdKyThiNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("LMS.Ovncr.Models.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LMS.Ovncr.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LMS.Ovncr.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("LMS.Ovncr.Models.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Ovncr.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LMS.Ovncr.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LMS.Ovncr.Models.AspNetUser", b =>
                {
                    b.Navigation("TbHocVienLopHocs");

                    b.Navigation("TbKetQuas");

                    b.Navigation("TbKyThis");

                    b.Navigation("TbLichPhongLabs");

                    b.Navigation("TbLopHocs");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbCauHoi", b =>
                {
                    b.Navigation("TbTraLois");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbComputer", b =>
                {
                    b.Navigation("TbHocVienLopHocs");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbDanhMucCauHoi", b =>
                {
                    b.Navigation("TbCauHois");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbKichBan", b =>
                {
                    b.Navigation("TbKetQuas");

                    b.Navigation("TbKichBanNhoms");

                    b.Navigation("TbKichBanSoDoMangs");

                    b.Navigation("TbLopHocKichBans");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbKieuDanhGium", b =>
                {
                    b.Navigation("TbKichBans");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbKyThi", b =>
                {
                    b.Navigation("TbTraLois");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbLopHoc", b =>
                {
                    b.Navigation("TbHocVienLopHocs");

                    b.Navigation("TbKetQuas");

                    b.Navigation("TbLopHocKichBans");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbNhom", b =>
                {
                    b.Navigation("TbKichBanNhoms");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbProjectOpenStack", b =>
                {
                    b.Navigation("TbComputers");

                    b.Navigation("TbGiamSats");

                    b.Navigation("TbInstances");

                    b.Navigation("TbLichPhongLabs");

                    b.Navigation("TbLopHocs");
                });

            modelBuilder.Entity("LMS.Ovncr.Models.TbSoDoMang", b =>
                {
                    b.Navigation("TbKichBanSoDoMangs");

                    b.Navigation("TbSoDoMangMays");
                });
#pragma warning restore 612, 618
        }
    }
}
